### ISSUE TITLE
Error, please assist.

### ISSUE THREAD

**Issue by virtualbeck** [studio24/bitbucket-bulk-add-hook#7]
`PHP Fatal error:  Call to undefined function curl_init() in /home/mikebeck/Projects/bitbucket-bulk-add-hook-master/bitbucket-bulk-add-hook.php on line 244`

**Comment by virtualbeck** [comment]
my line 244 is the same as line 259 here

```
    $curl = curl_init();
```

**Comment by simonrjones** [comment]
hi 

You need CURL installed in order to use this script, see http://php.net/manual/en/curl.installation.php

CURL does tend to be installed by default in many hosting environments, you may want to ask your hosting company about this.

If you're running this locally how are you running PHP? Is it via native PHP on a Mac/PC or via something like MAMP/WAMP?

best wishes,
Simon

**Comment by virtualbeck** [comment]
$ php -v
PHP 5.5.9-1ubuntu4.17 (cli) (built: May 19 2016 19:05:57) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies

$ curl -V
curl 7.35.0 (x86_64-pc-linux-gnu) libcurl/7.35.0 OpenSSL/1.0.1f zlib/1.2.8 libidn/1.28 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smtp smtps telnet tftp 
Features: AsynchDNS GSS-Negotiate IDN IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP

**Comment by virtualbeck** [comment]
Running locally, and thanks for your reply!

**Comment by simonrjones** [comment]
It sounds like you need to compile PHP with CURL support. See:  http://php.net/manual/en/curl.installation.php

and: http://stackoverflow.com/questions/2939820/how-to-enable-curl-installed-ubuntu-lamp-stack

This command will show you if you have CURL support or not.

```
php -i | grep curl
```

**Comment by virtualbeck** [comment]
This did the trick! Thanks!
